# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

file = "config.toml"

[bootstrap]
  autowhite_list = true
  content = ""
  provision = true
  x509_provision = false


[server]
  LogLevel = "info"
  ca_certs = ""
  http_port = "8190"
  mg_api_key = ""
  mg_bs_url = "http://localhost:9013"
  mg_certs_url = "http://localhost:9019"
  mg_pass = ""
  mg_user = ""
  mqtt_url = ""
  port = ""
  server_cert = ""
  server_key = ""
  things_location = "http://localhost:9000"
  tls = true
  users_location = ""

[[things]]
  name = "thing"

  [things.metadata]
    external_id = "xxxxxx"


[[channels]]
  name = "control-channel"

  [channels.metadata]
    type = "control"

[[channels]]
  name = "data-channel"

  [channels.metadata]
    type = "data"
