# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adapter-coap
spec:
  selector:
    app: {{ .Release.Name }}
    component: adapter-coap
  ports:
    - port: {{ .Values.adapter_coap.port }}
      protocol: UDP
      name: "udp-{{ .Values.adapter_coap.port }}"
    - port: {{ .Values.adapter_coap.port }}
      protocol: TCP
      name: "tcp-{{ .Values.adapter_coap.port }}"
