# Copyright (c) Magistrala
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
spec:
  selector:
    app: {{ .Release.Name }}
    component: auth
  ports:
    - protocol: TCP
      port: {{ .Values.auth.httpPort }}
      name: {{ .Release.Name }}-auth-http-{{ .Values.auth.httpPort }}
    - protocol: TCP
      port: {{ .Values.auth.grpcPort }}
      name: {{ .Release.Name }}-auth-grpc-{{ .Values.auth.grpcPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: auth
  ports:
    - protocol: TCP
      port: {{ .Values.auth.httpPort }}
      name: {{ .Release.Name }}-auth-http-{{ .Values.auth.httpPort }}
    - protocol: TCP
      port: {{ .Values.auth.grpcPort }}
      name: {{ .Release.Name }}-auth-grpc-{{ .Values.auth.grpcPort }}
  clusterIP: None
