# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.certs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-certs
spec:
  replicas: {{ default .Values.defaults.replicaCount .Values.certs.replicaCount | int64 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: certs
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.certs.httpPort }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}
        component: certs
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.certs.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-certs
          image: "{{ default (printf "%s/certs" .Values.defaults.image.rootRepository) .Values.certs.image.repository }}:{{ default .Values.defaults.image.tag .Values.certs.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.certs.image.pullPolicy }}
          env:
            - name: SMQ_JAEGER_URL
              value: {{ .Values.jaeger.enabled | ternary (printf "http://%s-jaeger-collector:%d/v1/traces" .Release.Name (.Values.jaeger.collector.service.otlp.http.port | int )) .Values.jaeger.externalUrl }}
            - name: SMQ_JAEGER_TRACE_RATIO
              value: {{ default .Values.jaeger.traceRatio .Values.certs.jaegerTraceRatio | quote }}
            - name: SMQ_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.certs.sendTelemetry | quote }}
            - name: SMQ_CERTS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.certs.logLevel | quote }}
            - name: SMQ_CERTS_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_CERTS_HTTP_PORT
              value: {{ .Values.certs.httpPort | quote }}
            - name: SMQ_CERTS_SDK_HOST
              value: {{ .Values.certs.sdkHost | quote }}
            - name: SMQ_CERTS_SDK_CERTS_URL
              value: {{ .Values.certs.sdkCertsUrl | quote }}
            - name: SMQ_CERTS_SDK_TLS_VERIFICATION
              value: {{ .Values.certs.sdkTlsVerification | quote }}
            - name: SMQ_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
            - name: SMQ_AUTH_GRPC_TIMEOUT
              value: {{ .Values.auth.grpcTimeout | quote }}
            - name: SMQ_CLIENTS_URL
              value: {{ .Release.Name }}-clients:{{ .Values.clients.httpPort }}
            - name: SMQ_CERTS_DB_HOST
            {{- if .Values.postgresqlcerts.enabled }}
              value: {{ .Release.Name }}-postgresqlcerts
            {{- else }}
              value: {{ .Values.postgresqlcerts.host | quote }}
            {{- end }}
            - name: SMQ_CERTS_DB_PORT
              value: {{ .Values.postgresqlcerts.port | quote }}
            - name: SMQ_CERTS_DB_NAME
              value: {{ .Values.postgresqlcerts.database | quote }}
            - name: SMQ_CERTS_DB_USER
              value: {{ .Values.postgresqlcerts.username | quote }}
            - name: SMQ_CERTS_DB_PASS
              value: {{ .Values.postgresqlcerts.password | quote }}
            - name: AM_CERTS_DB_SSL_MODE
              value: {{ .Values.certs.sslMode | quote }}
            - name: SMQ_CERTS_DB_SSL_MODE
              value: {{ .Values.certs.sslMode | quote }}
            - name: SMQ_CERTS_DB_SSL_CERT
              value: {{ .Values.certs.sslCert | quote }}
            - name: SMQ_CERTS_DB_SSL_KEY
              value: {{ .Values.certs.sslKey | quote }}
            - name: SMQ_CERTS_DB_SSL_ROOT_CERT
              value: {{ .Values.certs.sslRootCert | quote }}
            - name: SMQ_CERTS_SIGN_CA_PATH
              value: {{ .Values.certs.signCAPath }}
            - name: SMQ_CERTS_SIGN_CA_KEY_PATH
              value: {{ .Values.certs.signCAKeyPath }}
            - name: SMQ_CERTS_VAULT_HOST
              value: {{ .Values.certs.vault.url | quote }}
            - name:  SMQ_CERTS_VAULT_APPROLE_ROLEID
              value: {{ .Values.certs.vault.approleRoleid | quote }}
            - name: SMQ_CERTS_VAULT_APPROLE_SECRET
              value: {{ .Values.certs.vault.approleSecret | quote }}
            - name: SMQ_CERTS_VAULT_NAMESPACE
              value: {{ .Values.certs.vault.namespace | quote }}
            - name: SMQ_CERTS_VAULT_CLIENTS_CERTS_PKI_PATH
              value: {{ .Values.certs.vault.clientsCertsPkiPath | quote }}
            - name: SMQ_CERTS_VAULT_CLIENTS_CERTS_PKI_ROLE_NAME
              value: {{ .Values.certs.vault.clientsCertsPkiRoleName | quote }}
          ports:
            - containerPort: {{ .Values.certs.httpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.certs.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.certs.httpPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
{{- end }}
