# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-channels
spec:
  selector:
    app: {{ .Release.Name }}
    component: channels
  ports:
    - protocol: TCP
      port: {{ .Values.channels.httpPort }}
      targetPort: {{ .Values.channels.httpPort }}
      name: http
    - protocol: TCP
      port: {{ .Values.channels.grpcPort }}
      targetPort: {{ .Values.channels.grpcPort }}
      name: grpc
