# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clients
spec:
  selector:
    app: {{ .Release.Name }}
    component: clients
  ports:
    - port: {{ .Values.clients.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.clients.httpPort }}
    - port: {{ .Values.clients.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.clients.authGrpcPort }}
    - port: {{ .Values.auth.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.auth.httpPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clients-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: clients
  ports:
    - port: {{ .Values.clients.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.clients.httpPort }}
    - port: {{ .Values.clients.authGrpcPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.clients.authGrpcPort }}
    - port: {{ .Values.auth.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-clients-{{ .Values.auth.httpPort }}
  clusterIP: None
