# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Read_from_head   true
        Tag              kube.*

    [FILTER]
        Name         kubernetes
        Match        kube.*
        k8s-logging.exclude true
        Buffer_Size 256k

    [OUTPUT]
        Name        loki
        Match       *
        Host        supermq-loki-gateway
        Port        80
        Uri         /loki/api/v1/push
        Labels      job=fluent-bit
        Label_Keys  $kubernetes['namespace_name'], $kubernetes['pod_name']
        Line_Format json
        Auto_Kubernetes_Labels off
