# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-invitations
spec:
  selector:
    app: {{ .Release.Name }}
    component: invitations
  ports:
    - protocol: TCP
      port: {{ .Values.invitations.httpPort }}
      name: {{ .Release.Name }}-invitations-http
