# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |-
{{ .Values.prometheus.config | indent 4 }}
