{{- define "spicedb.envoy.config" -}}
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 50051
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: {{ .Release.Name }}-spicedb-envoy
                route_config:
                  name: {{ .Release.Name }}-spicedb_route
                  virtual_hosts:
                    - name: {{ .Release.Name }}-spicedb
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: spicedb_grpc_cluster
                            timeout: 0s
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: spicedb_grpc_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: spicedb_grpc_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-spicedb
                    port_value: {{ .Values.spicedb.grpc.port }}
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
{{- end -}}
