{{- $databaseHost := .Values.postgresqlspicedb.host | quote -}}
{{- if .Values.postgresqlspicedb.enabled -}}
  {{- $databaseHost = printf "%s-postgresqlspicedb" .Release.Name -}}
{{- end -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-spicedb-migrate-job
  labels:
    app: {{ .Release.Name }}
    component: spicedb-migrate-job
spec:
  template:
    spec:
      {{- with .Values.spicedb.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}-spicedb-migrate
          image: "{{ .Values.spicedb.image.repository }}:{{ .Values.spicedb.image.tag }}"
          imagePullPolicy:  {{ default .Values.defaults.image.pullPolicy .Values.spicedb.image.pullPolicy }}
          command: ["spicedb"]
          args:
            - migrate
            - head
            - --datastore-engine={{  include "validateSpiceDBDatastoreEngine"  .Values.spicedb.datastore.engine }}
            {{- if eq .Values.spicedb.datastore.engine "postgres" }}
            - --datastore-conn-uri=postgres://{{ .Values.postgresqlspicedb.username }}:{{ .Values.postgresqlspicedb.password }}@{{ $databaseHost }}:{{ .Values.postgresqlspicedb.port }}/{{ .Values.postgresqlspicedb.database }}
            {{- end }}
