apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spicedb-envoy
spec:
  selector:
    app: {{ .Release.Name }}
    component: spicedb-envoy
  ports:
    - port: {{ .Values.spicedb.grpc.port }}
      protocol: TCP
      name: {{ .Release.Name }}-spicedb-envoy-grpc-{{ .Values.spicedb.grpc.port }}
