# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.uibackend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.uibackend.httpPort }}
      targetPort: {{ .Values.uibackend.httpPort }}
  selector:
    app: {{ .Release.Name }}
    component: backend
{{- end }}

