# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "supermq.fullname" . | lower }}-users-vs
  labels:
    app: {{ include "supermq.fullname" . | lower }}
    component: users
spec:
  gateways:
    - {{ .Values.users.istioGateway | default "mg-istio-gateway" }}
  hosts:
    - {{ .Values.users.host | default (printf "%s-users.local" (include "supermq.fullname" .)) }}
  http:
    - name: primary
      match:
        - headers:
            domain-id:
              regex: {{ .Values.abRollout.canaryDomains | default "^$" | quote }}
      route:
        - destination:
            host: {{ include "supermq.fullname" . | lower }}-users
            subset: canary
          weight: 100
        - destination:
            host: {{ include "supermq.fullname" . | lower }}-users
            subset: stable
          weight: 0
    - name: default-traffic
      route:
        - destination:
            host: {{ include "supermq.fullname" . | lower }}-users
            subset: stable
          weight: 100
        - destination:
            host: {{ include "supermq.fullname" . | lower }}-users
            subset: canary
          weight: 0
