# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "supermq.fullname" . | lower }}-users
  labels:
    app: {{ include "supermq.fullname" . | lower }}
    component: users
spec:
  selector:
    app: {{ include "supermq.fullname" . | lower }}
    component: users
  ports:
    - protocol: TCP
      port: {{ .Values.users.httpPort }}
      targetPort: {{ .Values.users.httpPort }}
      name: users-http
