# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-config
  labels:
    app: {{ .Release.Name }}
    component: users
data:
  email.tmpl: |
    To: {{`{{range $index, $v := .To}}{{if $index}},{{end}}{{$v}}{{end}}`}}
    From: {{`{{.From}}`}}
    Subject: {{`{{.Subject}}`}}
    {{`{{.Header}}`}}
    You have initiated password reset.
    Follow the link below to reset password.
    {{`{{.Content}}`}}
    {{`{{.Footer}}`}}
