# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ws-adapter
spec:
  selector:
    app: {{ .Release.Name }}
    component: ws-adapter
  ports:
    - port: {{ .Values.adapter_ws.httpPort }}
      protocol: TCP
