apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Read_from_head   true
        Tag              kube.*

    [FILTER]
        Name         kubernetes
        Match        kube.*

    [OUTPUT]
        Name         loki
        Match        *
        Host         supermq-loki-gateway
        Port         80
        URI          /loki/api/v1/push

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: supermq
    meta.helm.sh/release-namespace: smq
  creationTimestamp: "2025-02-11T14:39:19Z"
  labels:
    app.kubernetes.io/instance: supermq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 3.2.4
    helm.sh/chart: fluent-bit-0.48.5
  name: supermq-fluent-bit
  namespace: smq
  resourceVersion: "7706687"
  uid: 7cdee6e7-dc24-43a2-9866-8b5a726b63b9
