# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb-reader
spec:
  selector:
    app: {{ .Release.Name }}
    component: influxdb-reader
  ports:
    - port: 8905
      protocol: TCP
      name: {{ .Release.Name }}-influxdb-writer-8905