# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.adapter_lora.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adapter-lora
spec:
  selector:
    app: {{ .Release.Name }}
    component: adapter-lora
  ports:
    - port: {{ .Values.adapter_lora.httpPort }}
      protocol: TCP
{{- end }}
