# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adapter-http
spec:
  selector:
    app: {{ .Release.Name }}
    component: adapter-http
  ports:
    - port: {{ .Values.adapter_http.httpPort }}
      protocol: TCP
