{{- define "magistrala.envoy.config" -}}
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 1883
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: {{ .Release.Name }}-mqtt-envoy
                cluster: {{ .Release.Name }}_mqtt_cluster
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.auth.grpcPort }}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: {{ .Release.Name }}-auth-envoy
                route_config:
                  name: auth_route
                  virtual_hosts:
                    - name: auth_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: {{ .Release.Name }}_auth_cluster
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.things.authGrpcPort }}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: {{ .Release.Name }}-things-envoy
                route_config:
                  name: things_route
                  virtual_hosts:
                    - name: things_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: {{ .Release.Name }}_things_cluster
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: {{ .Release.Name }}_mqtt_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: {{ .Release.Name }}_mqtt_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-mqtt
                    port_value: 1884
    - name: {{ .Release.Name }}_auth_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: {{ .Release.Name }}_auth_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-auth-headless
                    port_value: {{ .Values.auth.grpcPort }}

    - name: {{ .Release.Name }}_things_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: {{ .Release.Name }}_things_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Release.Name }}-things-headless
                    port_value: {{ .Values.things.authGrpcPort }}
admin:
    access_log_path: "/dev/null"
    address:
      socket_address:
          address: 0.0.0.0
          port_value: 8001

{{- end -}}
