# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-writer
spec:
  selector:
    app: {{ .Release.Name }}
    component: mongodb-writer
  ports:
    - port: {{ .Values.mongodb.writer.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-mongodb-writer-{{ .Values.mongodb.writer.httpPort }}
{{- end }}
