# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-reader
spec:
  selector:
    app: {{ .Release.Name }}
    component: mongodb-reader
  ports:
    - port: {{ .Values.mongodb.reader.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-mongodb-reader-{{ .Values.mongodb.reader.httpPort }}
{{- end }}
