# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.timescaledb.writer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-timescaledb-writer-config
data:
  subjects.toml: |
    # If you want to listen on all subjects, just pass one element ["channels.>"], otherwise
    # pass the list of subjects (e.g ["channels.<channel_id>", "channels.<channel_id>.sub.topic.x", ...]).
    [subjects]
    filter = ["channels.>"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescaledb-writer
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: timescaledb-writer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: timescaledb-writer
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.timescaledb.writer.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-timescaledb-writer-config
            optional: false
          name: timescaledb-writer-config
      containers:
        - name: {{ .Release.Name }}-timescaledb-writer
          image: "{{ default (printf "%s/timescale-writer" .Values.defaults.image.rootRepository) .Values.timescaledb.writer.image.repository }}:{{ default .Values.defaults.image.tag .Values.timescaledb.writer.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.timescaledb.writer.image.pullPolicy }}
          env:
            - name: MG_JAEGER_URL
              value: "http://{{ .Values.jaeger.fullnameOverride }}-collector:{{ .Values.jaeger.collector.service.otlp.http.port }}/v1/traces"
            - name: MG_JAEGER_TRACE_RATIO
              value: {{ default .Values.defaults.jaegerTraceRatio .Values.timescaledb.writer.jaegerTraceRatio | quote  }}
            - name: MG_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.timescaledb.writer.sendTelemetry | quote  }}
            - name: MG_ES_URL
              value: {{ .Values.defaults.eventStreamURL | quote }}
            - name: MG_TIMESCALE_WRITER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.timescaledb.writer.logLevel  | quote }}
            - name: MG_TIMESCALE_WRITER_HTTP_HOST
              value: "0.0.0.0"
            - name: MG_TIMESCALE_WRITER_HTTP_PORT
              value: {{ .Values.timescaledb.writer.http.port | quote }}
            - name: MG_TIMESCALE_WRITER_CONFIG_PATH
              value: "/config/subjects.toml"
            - name: MG_MESSAGE_BROKER_URL
              value: "nats://{{ .Release.Name }}-nats:{{ .Values.defaults.natsPort }}"
            - name: MG_TIMESCALE_HOST
            {{- if .Values.timescaledb.enabled }}
              value: "{{ .Release.Name }}-timescaledb"
            {{- else }}
              value: {{ .Values.timescaledb.host | quote }}
            {{- end }}
            - name: MG_TIMESCALE_PORT
              value: {{ .Values.timescaledb.port | quote }}
            - name: MG_TIMESCALE_USER
              value: {{ .Values.timescaledb.username | quote  }}
            - name: MG_TIMESCALE_PASS
              value: {{ .Values.timescaledb.password | quote  }}
            - name: MG_TIMESCALE_NAME
              value: {{ .Values.timescaledb.database | quote  }}
          ports:
            - containerPort: {{ .Values.timescaledb.writer.http.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config/subjects.toml
              name: timescaledb-writer-config
              subPath: subjects.toml
      {{- with .Values.timescaledb.writer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescaledb.writer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescaledb.writer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
