# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-users
spec:
  selector:
    app: {{ .Release.Name }}
    component: users
  ports:
    - protocol: TCP
      port: {{ .Values.users.httpPort }}
      name: {{ .Release.Name }}-users-http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-users-headless
spec:
  selector:
    app: {{ .Release.Name }}
    component: users
  ports:
    - protocol: TCP
      port: {{ .Values.users.httpPort }}
      name: {{ .Release.Name }}-users-http
  clusterIP: None
